# Generated by Django 2.2 on 2019-05-05 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=60)),
                ('status', models.CharField(choices=[('INA', 'Inactivo'), ('ACT', 'Activo')], default='ACT', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=20)),
                ('status', models.CharField(choices=[('INA', 'Inactivo'), ('ACT', 'Activo')], default='ACT', max_length=3)),
            ],
        ),
        
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateField()),
                ('price', models.CharField(max_length=10)),
                ('discount_price', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=256)),
                ('internalCode', models.CharField(default=None, max_length=20)),
                ('model', models.CharField(default=None, max_length=20)),
                ('size', models.CharField(default=None, max_length=5)),
                ('quantity', models.IntegerField(default=0)),
                ('presentation', models.CharField(default=None, max_length=5)),
                ('principalCode', models.CharField(default=None, max_length=10)),
                ('image_url', models.CharField(default=None, max_length=256)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('status', models.CharField(choices=[('INA', 'Inactivo'), ('ACT', 'Activo')], default='ACT', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=20)),
                ('status', models.CharField(choices=[('INA', 'Inactivo'), ('ACT', 'Activo')], default='ACT', max_length=3)),
                ('product', models.ManyToManyField(through='catalog.Price', to='catalog.Product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='typeProduct',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Type'),
        ),
        migrations.AddField(
            model_name='price',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product'),
        ),
        migrations.AddField(
            model_name='price',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Store'),
        ),
    ]
