# Generated by Django 2.1.7 on 2019-04-02 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateField()),
                ('name', models.CharField(max_length=256)),
                ('code', models.CharField(max_length=100)),
                ('brandName', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=256)),
                ('price', models.CharField(max_length=10)),
                ('discount_price', models.CharField(max_length=10)),
                ('principalCode', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('inactivo', 'Inactivo'), ('activo', 'Activo')], default='activo', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Store'),
        ),
    ]
