# Generated by Django 2.2 on 2019-04-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='price',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='presentation',
            field=models.CharField(default=None, max_length=5),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default=None, max_length=5),
        ),
        migrations.AddField(
            model_name='product',
            name='typeProduct',
            field=models.CharField(default=None, max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='principalCode',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
