# Generated by Django 2.2 on 2019-04-19 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_internalcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
